version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: "node:10.15.2-alpine"
    user: "node"
    container_name: node
    ports:
      - "3000"
    volumes:
      - .:/home/node/app