version: '3'
services:
  database:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    expose:
       - "27017"
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: "node:10.15.2-alpine"
    user: "node"
    container_name: node
    ports:
      - "5000:5000"
    links:
      - database
    volumes:
      - .:/home/node/app

